### ISSUE TITLE
Remove core::sync::atomic::* from the HAL

### ISSUE THREAD

**Issue by romancardenas** [riscv-rust/e310x-hal#53]
As discussed in yesterday's WG meeting, saying that the E310x chip supports atomic operations is... arguable, as LR/WC operations are not supported at all. I think we should remove dependencies to the `core::sync::atomic` module to allow compilations with the `riscv32imc` target and use atomic emulation such as `atomic-polyfill` when needed. Users can still compile for `riscv32imac` and use atomics if they want (provided that they only use simple load/store operations).

**Comment by jamesmunns** [comment]
@romancardenas can this be closed now that #54 has been merged?

**Comment by romancardenas** [comment]
Yep, thanks!
